{"id":"node_modules/inversify/lib/utils/exceptions.js","dependencies":[{"name":"C:\\inspace\\inspace_\\client\\node_modules\\inversify\\lib\\utils\\exceptions.js.map","includedInParent":true,"mtime":1623879764472},{"name":"C:\\inspace\\inspace_\\client\\package.json","includedInParent":true,"mtime":1624574747203},{"name":"C:\\inspace\\inspace_\\client\\node_modules\\inversify\\package.json","includedInParent":true,"mtime":1623879764472},{"name":"../constants/error_msgs","loc":{"line":4,"column":25},"parent":"C:\\inspace\\inspace_\\client\\node_modules\\inversify\\lib\\utils\\exceptions.js","resolved":"C:\\inspace\\inspace_\\client\\node_modules\\inversify\\lib\\constants\\error_msgs.js"}],"generated":{"js":"\"use strict\";\nObject.defineProperty(exports, \"__esModule\", { value: true });\nexports.isStackOverflowExeption = void 0;\nvar ERROR_MSGS = require(\"../constants/error_msgs\");\nfunction isStackOverflowExeption(error) {\n    return (error instanceof RangeError ||\n        error.message === ERROR_MSGS.STACK_OVERFLOW);\n}\nexports.isStackOverflowExeption = isStackOverflowExeption;\n"},"sourceMaps":{"js":{"version":3,"file":"exceptions.js","sourceRoot":"","sources":["../../src/utils/exceptions.ts"],"names":[],"mappings":";;;AAAA,oDAAsD;AAEtD,SAAgB,uBAAuB,CAAC,KAAY;IAChD,OAAO,CACH,KAAK,YAAY,UAAU;QAC3B,KAAK,CAAC,OAAO,KAAK,UAAU,CAAC,cAAc,CAC9C,CAAC;AACN,CAAC;AALD,0DAKC","sourcesContent":[null]}},"error":null,"hash":"879e3e2c03b45854af23109d6b719309","cacheData":{"env":{}}}